import { inject, Injectable, signal } from '@angular/core';
import { tap, catchError, throwError } from 'rxjs';
import { Hero, HeroFormVal } from '../models/hero.model';
import { HeroApi } from './hero-api';
import { Router } from '@angular/router';

@Injectable({
  providedIn: 'root',
})
export class Heroes {
  private readonly heroApi = inject(HeroApi);
  private readonly router = inject(Router);

  private readonly heroesSource = signal<Hero[]>([]);
  readonly heroes = this.heroesSource.asReadonly();

  loadHeroes(): void {
    // simulates basic cache
    if (this.heroes().length) {
      return
    }
    this.heroApi.getAllHeroes().subscribe({
      next: (data) => this.heroesSource.set(data),
    });
  }

  addHero(hero: HeroFormVal) {
    // id that should be generated by DB
    const heroWithId: Hero = {
      ...hero,
      id: crypto.randomUUID()
    };

    return this.heroApi.addHero(heroWithId).pipe(
      tap(() => {
        this.heroesSource.update(heroes => [...heroes, heroWithId]);
        this.router.navigate(['/home']);
      }),
      catchError(error => {
        // add dialog or snackbar here
        console.error('Failed to add hero:', error);
        
        return throwError(() => error);
      })
    )
  }

  removeHero(id: string) {
    this.heroesSource.update(heroes => heroes.filter(hero => hero.id !== id));
  }
}